version: '3.7'

services:
  postgresql-slave:
    image: bitnami/postgresql:DEVOPS_IMAGE_TAG
    container_name: postgresql-slave
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=DEVOPS_PRIMARY_HOST  # Replace with the actual IP of the master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=my_repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=my_repl_password
    volumes:
      - ./postgresql.conf:/opt/bitnami/postgresql/conf/postgresql.conf
    network_mode: host
    restart: always
